### ISSUE TITLE
添加终端时密码有特殊字符会变转义

### ISSUE THREAD

**Issue by elkan1788** [wolfboys/opencron#11]
今天在添加WEB终端时，总是提示密码不正确，起初以为是密码的问题，但在本地SSH是可以正常登录的，最后加载源码，进一步DEBUG发现是因密码中包含了`&`特殊字符，结果在后面会转义成了`&amp;`，这个应该是JSONMapper转换中出错了，提交改进下。

**Comment by wolfboys** [comment]
fixed
